name: Image CI Build

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
      - test*
    paths-ignore:
      - 'docs/**'

# Since this workflow can execute on pull_request_target, drop all the
# permissions of the GITHUB_TOKEN except `contents: read` for access to the repo
# with the actions/checkout action.
permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - name: tetragon
            dockerfile: ./Dockerfile
          - name: tetragon-operator
            dockerfile: ./Dockerfile.operator
          - name: tetragon-rthooks
            dockerfile: ./Dockerfile.rthooks
    env:
      IMAGE: ghcr.io/3u13r/${{ matrix.name }}-ci

    steps:
      - name: Checkout main branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0
