name: Check docs links

on:
  pull_request:
    paths:
      - 'README.md'
      - 'docs/content/**.md'
      - '.github/lychee.toml'
      - '.github/workflows/check-links-pr.yaml'
    branches:
      - 'main'

jobs:
  links-checker:
    runs-on: ubuntu-latest
    permissions: {} # lychee uses the GITHUB_TOKEN for authentication only
    env:
      PATCH_FILE: "additions.patch"
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod
