name: Check images digest for multi-arch

on:
  pull_request:
    paths:
      - '**[dD]ockerfile**'
      - '.github/workflow/digestcheck.yaml'
      - 'contrib/digestcheck.sh'
      - '!**vendor**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0   # because we also need the main branch
