name: Lint helm chart
on:
  push:
    branches:
    - main
    - v*
    paths:
    - 'install/kubernetes/**'
    - 'pkg/k8s/apis/cilium.io/client/crds/v1alpha1/*.yaml'
    - 'docs/content/en/docs/reference/helm-chart.md'
    - '.github/workflows/lint-helm.yaml'
  pull_request:
    paths:
    - 'install/kubernetes/**'
    - 'pkg/k8s/apis/cilium.io/client/crds/v1alpha1/*.yaml'
    - 'docs/content/en/docs/reference/helm-chart.md'
    - '.github/workflows/lint-helm.yaml'

permissions:
  pull-requests: write

env:
  MIN_K8S_VERSION: "1.30.0"
  # renovate: datasource=python-version
  PYTHON_VERSION: "3.12"

jobs:
  build-and-lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0