name: Lint protobuf API
on:
  push:
    branches:
      - main
      - v*
    paths:
      - api/**
      - docs/content/en/docs/reference/grpc-api.md
      - .github/workflows/lint-proto.yaml
  pull_request:
    paths:
      - api/**
      - docs/content/en/docs/reference/grpc-api.md
      - .github/workflows/lint-proto.yaml

jobs:
  lint-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Lint protobuf
        run: |
          echo "Linting protobuf files..."
