name: Packages e2e Tests

on:
  pull_request:
    paths-ignore:
    - "**.md"
    - 'docs/**'

jobs:
  standalone-tarball-builds:
    runs-on: ${{ (matrix.arch == 'arm64' && 'ubuntu-22.04-arm') || 'ubuntu-22.04' }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

  standalone-tarball-tests:
    needs: [standalone-tarball-builds]
    runs-on: ${{ (matrix.arch == 'arm64' && 'ubuntu-22.04-arm') || 'ubuntu-22.04' }}
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            match_arch: x86-64
          - arch: arm64
            match_arch: arm64
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0