name: Tetragon e2e Test
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  clusterName: tetragon-ci

jobs:
  prepare:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

  run-e2e-test:
    needs: prepare
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    name: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04]
    steps:
    - name: Checkout Code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        path: go/src/github.com/cilium/tetragon/
