name: tetragon-rthooks test
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  prepare:
    name: Build tetragon-rthooks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      agentImage: ${{ steps.vars.outputs.agentImage }}
      operatorImage: ${{ steps.vars.outputs.operatorImage }}
      rthooksImage: ${{ steps.vars.outputs.rthooksImage }}
    concurrency:
      group: ${{ github.ref }}-rthooks-build
      cancel-in-progress: true
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        path: go/src/github.com/cilium/tetragon/

  test:
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
        fail-fast: false
        matrix:
           cri:
            - "containerd"
            - "crio"
    concurrency:
      group: ${{ github.ref }}-rthooks-test-${{ matrix.cri }}
      cancel-in-progress: true
    steps:
    - name: Checkout Code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        path: go/src/github.com/cilium/tetragon/
