name: Windows Build and Smoke

on:
  workflow_dispatch:
    inputs:
      PR-number:
        required: true
        type: string
      context-ref:
        required: true
        type: string
      SHA:
        required: true
        type: string
      base-SHA:
        required: true
        type: string
  push:
    branches:
      - main
      - v*
    paths-ignore:
      - "**.md"

env:
  TEMP: D:\temp
  GOARCH: amd64
  GOOS: windows
  GOCACHE: D:\gocache
  GOMODCACHE: D:\gomodcache
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

permissions:
  contents: read

jobs:
  commit-status-start:
    name: Commit Status Start
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Set initial commit status
        uses: 3u13r/tetragon-workflows/.github/actions/set-commit-status@main
        with:
          sha: ${{ inputs.SHA || github.sha }}

  windows-ebpf-prog-build:
    needs: commit-status-start
    name: Build Windows ebpf programs
    runs-on: windows-2022
    timeout-minutes: 25

    permissions:
      contents: read

    steps:
      - name: Create Temp Directory
        shell: pwsh
        run: mkdir D:\temp

      - name: Checkout Tetragon Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.SHA || github.sha }}
          submodules: true

  commit-status-final:
    if: ${{ always() }}
    name: Commit Status Final
    needs: windows-ebpf-prog-build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Set final commit status
        uses: 3u13r/tetragon-workflows/.github/actions/set-commit-status@main
        with:
          sha: ${{ inputs.SHA || github.sha }}
          status: ${{ needs.windows-ebpf-prog-build.result == 'success' && 'success' || 'failure' }}
