name: Windows Build and Smoke

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
      - v*
    paths-ignore:
      - "**.md"

env:
  TEMP: D:\temp
  GOARCH: amd64
  GOOS: windows
  GOCACHE: D:\gocache
  GOMODCACHE: D:\gomodcache
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  windows-ebpf-prog-build:
    name: Build Windows ebpf programs
    runs-on: windows-2022
    timeout-minutes: 25

    permissions:
      contents: read

    steps:
      - name: Create Temp Directory
        shell: pwsh
        run: mkdir D:\temp

      - name: Checkout Tetragon Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
